name: Odoo Git Guidelines / Commit Name
description: Check if commit name follows Odoo guidelines

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Checking Commit Message
        # Pipe commit message to grep. Note that RegEx is escaped: \[\w+\].+
        run: |
          echo "${{github.event.head_commit.message}}" | grep -P "\[\w+\].+"
