name: Odoo Git Guidelines / Commit Name
description: Check if commit name follows Odoo guidelines

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - name: Checking Commit Message
      shell: ubuntu-latest
      # Pipe commit message to grep. Note that RegEx is escaped: \[\w+\].+
      run: |
        echo "${{github.event.head_commit.message}}" | grep -P "\[\w+\].+"
